# Generated by Django 5.1.7 on 2025-03-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("iglesia", "Iglesia"),
                    ("celebracion", "Celebración"),
                    ("otros", "Otros"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="foto",
            name="imagen",
            field=models.ImageField(upload_to="fotos/"),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "foto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="fotos.foto",
                    ),
                ),
            ],
        ),
    ]
