# Generated by Django 5.1.7 on 2025-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0002_alter_foto_categoria_alter_foto_imagen_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="foto",
            name="hash_imagen",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
