# Generated by Django 5.0 on 2025-05-04 01:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0003_foto_hash_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
