# Generated by Django 5.0 on 2025-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fotos", "0004_alter_foto_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="foto",
            name="url_imagen",
            field=models.URLField(blank=True, null=True),
        ),
    ]
