services:
  - type: web
    name: comunion-galeria
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn comunion.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: comunion.settings
      - key: PYTHON_VERSION
        value: "3.10"
